jwt:
  secret: 28bca96d37984b54839296dd9410748f

spring:
  datasource:
    #数据库url
    url: jdbc:mysql://mysql:3306/solitaire?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
    #数据库用户名
    username: root
    #数据库用户密码
    password: 413cc0869e8c401298ef740edbb28c96
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080



solitaire:
  wechatAppkey: 小程序的appid
  wechatAppsecret: 小程序的secret

aliyun:
  ossAccesskey: 阿里云oss key
  ossAccessecret: 阿里云oss secret
  ossEndpoint: 阿里云oss endpoint 节点
  ossBucket: 阿里云oss bucket名字
  ossBinddoman: 阿里云 oss 绑定的域名 httos://xxx.com/